const foods = [
  {
    id: 1,
    name: "Grilled Chicken Breast",
    calories: 165,
    protein: 31, // grams
    fat: 3.6, // grams
    carbs: 0, // grams
    servingSize: "100g",
    mealType: "Lunch",
    dateLogged: "2024-09-25",
  },
  {
    id: 2,
    name: "Avocado Toast",
    calories: 250,
    protein: 6,
    fat: 18,
    carbs: 22,
    servingSize: "1 slice of bread with 1/2 avocado",
    mealType: "Breakfast",
    dateLogged: "2024-09-25",
  },
  {
    id: 3,
    name: "Greek Yogurt",
    calories: 100,
    protein: 10,
    fat: 2,
    carbs: 6,
    servingSize: "100g",
    mealType: "Snack",
    dateLogged: "2024-09-25",
  },
  {
    id: 4,
    name: "Salmon Salad",
    calories: 350,
    protein: 30,
    fat: 20,
    carbs: 12,
    servingSize: "200g",
    mealType: "Dinner",
    dateLogged: "2024-09-24",
  },
  {
    id: 5,
    name: "Banana",
    calories: 90,
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    servingSize: "1 medium banana",
    mealType: "Snack",
    dateLogged: "2024-09-24",
  },
  {
    id: 6,
    name: "Steak and Veggies",
    calories: 450,
    protein: 35,
    fat: 30,
    carbs: 15,
    servingSize: "250g",
    mealType: "Dinner",
    dateLogged: "2024-09-23",
  },
];
